name: Build Firmware

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - dev

    # Publish `v1.2.3` tags as releases.
    # tags:
    #   - v*

jobs:
  build:
    name: Compile for ESP12s
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout CDEM library
      uses: actions/checkout@v2
      with:
        repository: connected-digital-energy-meter/connected-digital-energy-meter
        ref: master
        path: CustomLibrary_connected-digital-energy-meter # must contain string "Custom"

    - name: Compile Firmware
      uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: esp8266:esp8266:generic:xtal=80,vt=flash,exception=disabled,stacksmash=disabled,ssl=all,mmu=3232,non32xfer=fast,ResetMethod=nodemcu,CrystalFreq=26,FlashFreq=40,FlashMode=dout,eesz=1M64,led=2,sdk=nonosdk_190703,ip=lm2f,dbg=Disabled,lvl=None____,wipe=none,baud=115200
        platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
        required-libraries: PubSubClient@2.8,ArduinoJson@6.18.0
